server {

    listen 80;

    server_name localhost;

    root /var/www/html/public;

    index index.php;

    charset utf-8;

    location = / {
        root /var/www/html/frontend;
        try_files /index.html =404;
    }

    location ^~ /api/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location / {
        try_files $uri $uri/ @frontend;
    }

    location @frontend {
        root /var/www/html/frontend;
        try_files $uri $uri/ /index.html;
    }

    location = /favicon.ico {

        access_log off;

        log_not_found off;

    }

    location = /robots.txt {

        access_log off;

        log_not_found off;

    }

    location ~ \.php$ {

        fastcgi_pass app:9000;

        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

    }

    location ~ /\.(?!well-known).* {

        deny all;

    }

}